print("ProfileKu")
print("="*30)
nama=input("Nama : ")
print(type(nama))
fakultas=input("Fakultas : ")
print(type(fakultas))
matkul=input("Mata Kuliah : ")
print(type(matkul))
akhir=int(input("Nilai AKhir : "))
print(type(akhir))
profile=tuple(input("Profile : "))
print(type(profile))